name: TrafficLightController
description: A new Flutter project.

publish_to: 'none'

version: 0.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_bluetooth_serial: ^0.2.2
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
